config/routes.rb
Rails.application.routes.draw do
resources :cars

  get 'notes/create'

  get 'ratings/update'

  get 'cars/:id/journal' => 'cars#get_car_journal'

  devise_for :users

  root 'welcome#index'
  get 'garages/' => 'garages#search', as: 'search_garages'

  resources :garages do
    resources :services
  end

  resources :journals do 
    resources :notes
  end

  resources :comments

  resources :ratings, only: :update

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :user
  has_one :journal
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_one :note
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :garage
  belongs_to :user

  def get_user
    User.find(self.user_id)
  end
end

app/models/garage.rb
class Garage < ActiveRecord::Base
    geocoded_by :address

    has_many :ratings
    has_many :comments
    # for seed
    # before_validation :geocode

    scope :search_query, lambda { |query|
      query = '' if query.blank?

      terms = query.downcase.split(/\s+/)

      terms = terms.map { |e|
        ('%' + e.gsub('*', '%') + '%').gsub(/%+/, '%')
      }

      num_or_conds = 2

      where(
        terms.map { |term|
          "(LOWER(garages.name) LIKE LOWER(?) OR LOWER(garages.address) LIKE LOWER(?))"
        }.join(' AND '),
        *terms.map { |e| [e] * num_or_conds }.flatten
      )
    }

    scope :average_cost, -> (average_cost) { where average_cost: Integer(average_cost) === 0 ? [1,2,3] : average_cost }

    def average_rating
      ratings.sum(:score) / ratings.size
    end
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :car
  has_many :notes
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :journal
  belongs_to :category
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :garage
  belongs_to :user
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :garage
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :ratings
    has_many :comments
    has_many :cars

    def get_rating(garage_id)
        Rating.where(user_id: self.id, garage_id: garage_id)
    end
end

app/controllers/cars_controller.rb
require 'pry'
class CarsController < ApplicationController
  def index
    @cars = Car.where(user_id: current_user.id)
    if !@cars.any?
      redirect_to new_car_path
    end
  end

  def get_car_journal
    journal = Journal.where(car_id: params[:id])[0]
    if (!journal) 
      journal = Journal.create(car_id: params[:id])
    end
    respond_to do |format|
      format.json { render json: {journal_id: journal.id} }
    end
  end

  def new
    @car = Car.new
  end

  def create
    params = car_params
    params['year'] = params['year'].to_i
    params[:user_id] = current_user.id
    @car = Car.create(params)
    redirect_to cars_path
  end

  def update
  end

  private
    def car_params
        params.require(:car).permit(:make, :color, :fuel, :year)
    end
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController
	before_action :all_garages, only: [:new]
	respond_to :html, :js
	before_filter :authenticate_user!, except: [:search]

	def show
		@comment = Comment.new
		@comments = get_comments.reverse
		@garage = Garage.find(params[:id])
	end

	def search
		@found_garages = result_garages = Garage.search_query(params[:search]).average_cost(params[:average_cost])
		result_garages = assign_rating

		respond_to do |format| 
			format.json {render json: result_garages}
		end
	end

	def new
		@garage = Garage.new
	end

	def create
		@garage = Garage.create(garage_params)
		redirect_to root_path
	end

	private
		def assign_rating
			@found_garages.map do |garage|
				if current_user
					rating = Rating.where(garage_id: garage.id, user_id: current_user.id).first 
					unless rating 
					    rating = Rating.create(garage_id: garage.id, user_id: current_user.id, score: 0)
					end
					
					{ garage: garage, rating: { id: rating.id, average: garage.average_rating } }
				else 
					{ garage: garage, rating: { average: garage.average_rating } }
				end
			end
		end

		def all_garages
			@garages = Garage.all
		end

		def garage_params
	      params.require(:garage).permit(:name, :address, :latitude, :longitude, :average_cost, :start_time, :end_time, :working_days)
	    end

	    def get_comments
	    	comments = Comment.where(garage_id: params[:id])
	    	comments.map do |comment|
	    		{ commentObj: comment, user_name: comment.get_user.full_name, user_score: comment.get_user.get_rating(comment.garage_id).first.score }
	    	end
	    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    note_params = get_note_params
    note_params['journal_id'] = params[:journal_id]
    note_params['category_id'] = Category.where(name: params[:note][:category_id])[0].id
    @note = Note.create(note_params)

    respond_to do |format|
        format.json { render json: { note: @note, categoryName: params[:note][:category_id]} }
    end
  end

  private
    def get_note_params
        params.require(:note).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/garages_helper.rb
module GaragesHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/garages/_form.html.slim
= form_for @garage, html: {name: "cGarageForm", novalidate: true} do |f|
    .field
        = f.label :name, "Название"
        = f.text_field :name, autofocus: true, required: true, "ng-model": "value"
        label.error ng-show="cGarageForm['garage[name]'].$error.required && cGarageForm['garage[name]'].$touched" Поле Имя не может быть пустым

    .field
        = f.label :address, "Адрес"
        = f.text_field :address, autocomplete: "off", required: true, "ng-model": "value1"
        label.error ng-show="cGarageForm['garage[address]'].$invalid && cGarageForm['garage[address]'].$touched" Поле Адрес не может быть пустым
        label.error ng-show="cGarageForm['garage[address]'].invalidAddress && cGarageForm['garage[address]'].$dirty" Был введен некорректный адрес
    .field.half-field
        = f.label :start_time, "Начало работы"
        = f.text_field :start_time, required: true, "ng-model": "value2"
        label.error ng-show="cGarageForm['garage[start_time]'].$invalid && cGarageForm['garage[start_time]'].$touched" Поле Время Открытия не может быть пустым
    .field.half-field
        = f.label :end_time, "Конец работы"
        = f.text_field :end_time, required: true, "ng-model": "value3"
        label.error ng-show="cGarageForm['garage[end_time]'].$invalid && cGarageForm['garage[end_time]'].$touched" Поле Время Закрытия не может быть пустым
    .field.half-field
        = f.label :phone, "Телефон"
        = f.text_field :phone, required: true, "ng-model": "value4"
        label.error ng-show="cGarageForm['garage[phone]'].$invalid && cGarageForm['garage[phone]'].$touched" Поле Телефон не может быть пустым
    .field.half-field
        = f.label :average_cost, "Ценовая категория"
        = f.select :average_cost, [['Дешево', 1], ['Нормально', 2], ['Дорого', 3]], prompt: "Выберите категорию", required: true, "ng-model": "value5"
        label.error ng-show="cGarageForm['garage[average_cost]'].$invalid && cGarageForm['garage[average_cost]'].$touched" Поле Ценовая Категория не может быть пустым
    .field.working-days
        .week-day Пн.
        .week-day Вт.
        .week-day Ср.
        .week-day Чт.
        .week-day Пт.
        .week-day Сб.
        .week-day Вс.
    = f.hidden_field :working_days, value: "", class: "week-days"
    = f.hidden_field :latitude, value: "", class: "lat"
    = f.hidden_field :longitude, value: "", class: "lng"

    .actions.field
      = f.submit "Create", "ng-disabled": 'cGarageForm.$invalid', class: "button small create-garage"

app/views/garages/new.html.slim
.main-container
    = link_to "На главную", root_path
    .garage-form ng-controller="CreateGarageController"
        = render ("form")

        .map-container ng-controller="MapController"
            #map.form-map

        = content_tag :div, class: "temp_information", data: {garages: @garages} do

app/views/garages/show.html.slim
.main-container.garage-page
    = link_to "На главную", root_path
    .row
        .main-garage-info.column.small-12.large-6
            .callout
                h5 
                    = @garage.name
                h5.pull-right
                    = link_to "Показать услуги", garage_services_path(@garage[:id])
                table
                    tbody
                        tr
                            td Адрес
                            td 
                                = @garage.address 
                        tr
                            td Время работы
                            td 
                                = @garage.start_time
                                |-
                                = @garage.end_time
                        tr
                            td Ценовая категория
                            td
                                - for i in (0..@garage.average_cost-1)
                                    span.glyphicon.glyphicon-usd
                        tr
                            td.average-rating Средняя оценка
                            td 
                                = @garage.average_rating
                .add-service-link
                    span Не нашли услугу, которой воспользовались на СТО? 
                    = link_to "Добавьте!", new_garage_service_path(@garage[:id])
            
        .map-container.column.small-12.large-6 ng-controller="MapController"
            #map.form-map-garage
    
    .row
        .comment-container.column
            .header
                h5 Комментарии:
            .comments
                - @comments.each do |comment|
                    .comment
                        .callout.secondary.comment-header
                            = comment[:commentObj].created_at.to_json
                            |  by 
                            = comment[:user_name]
                            - if current_user.id == comment[:commentObj].user_id
                                span.pull-right
                                    = link_to "Удалить", comment_path(comment), method: :delete, remote: true, class: "detele-comment"

                            .user-score.show-score data-score=comment[:user_score]
                        .callout.comment-content 
                            = comment[:commentObj].content
            
        .create-comment.column
            h5 Создать коментарий
            = form_for @comment, remote: true do |f|
                = f.text_area :content, class: 'comment-text'
                = f.hidden_field :garage_id, value: @garage.id
                = f.submit "Сохранить", class: 'button small'